[package]
name = "hotklicker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.1.2"
inputbot = "0.5.1"
serde = {version = "1.0.163", features = ["derive"]}
serde_yaml = "0.9"
