hotkeys:
  loot_below:
    key: l
    commands:
      - mouse_cmd: left click
        modifier: alt
        position_type: absolute
        position_coords:
          - 870
          - 490
  click_repeatedly:
    key: p
    loop_delay: 1000
    commands:
      - mouse_cmd: left click
        position_type: relative
        position_coords:
          - 0
          - 0
  loot_arround:
    key: caps lock
    commands:
      - mouse_cmd: left click
        modifier: alt
        position_type: absolute
        position_coords:
          - 870
          - 490
      - mouse_cmd: left click
        modifier: alt
        position_type: relative
        position_coords:
          - 0
          - -70
      - mouse_cmd: left click
        modifier: alt
        position_type: relative
        position_coords:
          - 70
          - 0
      - mouse_cmd: left click
        modifier: alt
        position_type: relative
        position_coords:
          - 0
          - 70
      - mouse_cmd: left click
        modifier: alt
        position_type: relative
        position_coords:
          - 0
          - 70
      - mouse_cmd: left click
        modifier: alt
        position_type: relative
        position_coords:
          - -70
          - 0
      - mouse_cmd: left click
        modifier: alt
        position_type: relative
        position_coords:
          - -70
          - 0
      - mouse_cmd: left click
        modifier: alt
        position_type: relative
        position_coords:
          - 0
          - -70
      - mouse_cmd: left click
        modifier: alt
        position_type: relative
        position_coords:
          - 0
          - -70